exp_name: baseline_comparison
model_name: resnet18_skip
seed: 42
deterministic: true
train_dir: ../data_samples/Train
test_dir: ../data_samples/Test
img_size: 512
batch_size: 8
num_workers: 2
val_split: 0.2
pin_memory: true
mean:
- 0.5708
- 0.6013
- 0.5365
std:
- 0.1896
- 0.1569
- 0.1145
num_classes: 2
pretrained: true
epochs: 20
lr: 0.0001
weight_decay: 0.0005
optimizer: AdamW
momentum: 0.9
scheduler: CosineAnnealingLR
T_max: 100
eta_min: 1.0e-06
warmup_epochs: 3
validate_every: 2
save_every: 10
log_interval: 10
grad_clip: 1.0
early_stop: true
patience: 15
min_delta: 0.001
device: cuda
use_amp: false
batch_sizes:
  vanilla_resnet18: 8
  resnet18_focal: 8
  resnet18_skip: 8
  full_improved: 8
checkpoint_dir: checkpoints
log_dir: logs
result_dir: results
